[package]
name = "rsgenetic"
version = "0.6.0"
authors = ["Mathieu De Coster <mth.decoster@gmail.com>"]
description = "A library providing genetic algorithm execution."
repository = "https://github.com/m-decoster/RsGenetic"
readme = "README.md"
keywords = ["genetic"]
license = "Apache-2.0"

[dependencies]
rand = "0.3"
time = "0.1"
